"""Render an intel report (+ run-over-run changes) to JSON and Markdown."""

from __future__ import annotations

import json

from competitive_intel.models import Change, IntelReport, ThreatLevel

_BADGE = {
    ThreatLevel.CRITICAL: "🔴 Critical",
    ThreatLevel.HIGH: "🟠 High",
    ThreatLevel.MEDIUM: "🟡 Medium",
    ThreatLevel.LOW: "🟢 Low",
}


def render_json(report: IntelReport, changes: list[Change]) -> str:
    """Serialize the brief (report + changes) as pretty JSON."""
    payload = {
        "report": report.model_dump(mode="json"),
        "changes": [c.model_dump(mode="json") for c in changes],
    }
    return json.dumps(payload, indent=2)


def _cell(text: str, limit: int = 140) -> str:
    text = " ".join((text or "").split())
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text.replace("|", "\\|")


def render_markdown(report: IntelReport, changes: list[Change]) -> str:
    badge = _BADGE[report.overall_threat_level]
    lines: list[str] = []

    lines.append(f"# Competitive Intelligence Brief — {report.company}")
    lines.append("")
    lines.append(f"**Market:** {report.vertical}  ")
    lines.append(f"**Overall competitive threat:** {badge}  ")
    lines.append(f"**Competitors tracked:** {len(report.competitors)}  ")
    lines.append(f"**Model:** `{report.model}`  ")
    lines.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    # -- What changed since last run --
    lines.append("## What Changed Since Last Run")
    lines.append("")
    if changes:
        for ch in changes:
            who = f" — **{ch.competitor}**" if ch.competitor else ""
            lines.append(f"- _{ch.kind.value.replace('_', ' ')}_{who}: {ch.summary}")
            if ch.before or ch.after:
                lines.append(f"  - before: {_cell(ch.before or '—', 200)}")
                lines.append(f"  - after: {_cell(ch.after or '—', 200)}")
        lines.append("")
    else:
        lines.append("_No prior run to compare against (this is the baseline)._")
        lines.append("")

    # -- Market summary --
    lines.append("## Market Landscape")
    lines.append("")
    lines.append(report.market_summary)
    lines.append("")

    # -- Competitor table --
    lines.append("## Competitors")
    lines.append("")
    if report.competitors:
        lines.append("| Competitor | Positioning | Pricing | Key strengths |")
        lines.append("|---|---|---|---|")
        for c in report.competitors:
            strengths = "; ".join(c.strengths[:3]) if c.strengths else "—"
            lines.append(
                f"| {_cell(c.name, 40)} | {_cell(c.positioning)} | "
                f"{_cell(c.pricing, 60)} | {_cell(strengths)} |"
            )
        lines.append("")

    # -- Threat register --
    lines.append("## Threat Register")
    lines.append("")
    if report.threats:
        for i, t in enumerate(report.threats_by_severity(), start=1):
            who = f" ({t.competitor})" if t.competitor else ""
            lines.append(f"### {i}. {_BADGE[t.severity]}{who}")
            lines.append("")
            lines.append(t.description)
            lines.append("")
            lines.append(f"**Recommendation:** {t.recommendation}")
            lines.append("")
    else:
        lines.append("_No material threats identified._")
        lines.append("")

    # -- Sources --
    if report.sources:
        lines.append("## Sources")
        lines.append("")
        for url in report.sources:
            lines.append(f"- {url}")
        lines.append("")

    u = report.token_usage
    lines.append("---")
    lines.append(
        f"_Generated by the Lumifie Consulting Competitive Intelligence Agent. "
        f"Tokens: {u.get('input_tokens', 0):,} in / {u.get('output_tokens', 0):,} out. "
        f"Informational only — verify before acting._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
