"""Render a :class:`ContractReport` to JSON and to a formatted markdown summary."""

from __future__ import annotations

from contract_intelligence.models import ClauseCategory, ContractReport, RiskLevel

_SEVERITY_BADGE = {
    RiskLevel.CRITICAL: "🔴 Critical",
    RiskLevel.HIGH: "🟠 High",
    RiskLevel.MEDIUM: "🟡 Medium",
    RiskLevel.LOW: "🟢 Low",
}

# Stable display order for clause sections.
_CATEGORY_ORDER = [
    ClauseCategory.PAYMENT_TERMS,
    ClauseCategory.TERMINATION,
    ClauseCategory.IP_OWNERSHIP,
    ClauseCategory.LIABILITY,
    ClauseCategory.DISPUTE_RESOLUTION,
    ClauseCategory.OTHER,
]


def render_json(report: ContractReport, *, indent: int = 2) -> str:
    """Serialize the report to a stable, pretty-printed JSON string."""
    return report.model_dump_json(indent=indent)


def _quote(text: str, limit: int = 600) -> str:
    text = " ".join(text.split())
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def render_markdown(report: ContractReport) -> str:
    """Render an executive-friendly markdown summary."""
    badge = _SEVERITY_BADGE[report.overall_risk_level]
    lines: list[str] = []

    lines.append(f"# Contract Analysis — {report.contract_name}")
    lines.append("")
    lines.append(f"**Overall risk:** {badge}  ")
    lines.append(f"**Pages analyzed:** {report.page_count}  ")
    lines.append(f"**Model:** `{report.model}`  ")
    lines.append(
        f"**Analyzed at:** {report.analyzed_at.strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    # -- Risk register, most severe first --
    lines.append("## Risk Register")
    lines.append("")
    if report.risks:
        counts: dict[RiskLevel, int] = {}
        for r in report.risks:
            counts[r.severity] = counts.get(r.severity, 0) + 1
        tally = ", ".join(
            f"{counts[lvl]} {lvl.label.lower()}"
            for lvl in (RiskLevel.CRITICAL, RiskLevel.HIGH, RiskLevel.MEDIUM, RiskLevel.LOW)
            if counts.get(lvl)
        )
        lines.append(f"_{len(report.risks)} risk(s) identified: {tally}._")
        lines.append("")
        for i, risk in enumerate(report.risks_by_severity(), start=1):
            lines.append(
                f"### {i}. {_SEVERITY_BADGE[risk.severity]} — {risk.title}"
            )
            lines.append(f"*Category: {risk.category.label}*")
            lines.append("")
            lines.append(risk.description)
            lines.append("")
            lines.append(f"**Recommendation:** {risk.recommendation}")
            if risk.related_excerpt:
                lines.append("")
                lines.append(f"> {_quote(risk.related_excerpt)}")
            lines.append("")
    else:
        lines.append("_No risks were identified._")
        lines.append("")

    # -- Extracted clauses, grouped by category --
    lines.append("## Key Clauses")
    lines.append("")
    grouped = report.clauses_by_category()
    if report.clauses:
        for category in _CATEGORY_ORDER:
            clauses = grouped.get(category)
            if not clauses:
                continue
            lines.append(f"### {category.label}")
            lines.append("")
            for clause in clauses:
                page = f" _(p. {clause.page})_" if clause.page else ""
                lines.append(f"- **{clause.title}**{page}: {clause.summary}")
                lines.append(f"  > {_quote(clause.verbatim_excerpt)}")
            lines.append("")
    else:
        lines.append("_No clauses were extracted._")
        lines.append("")

    # -- Footer --
    u = report.token_usage
    lines.append("---")
    lines.append(
        f"_Generated by the Lumifie Consulting Contract Intelligence Agent. "
        f"Token usage: {u.input_tokens:,} in / {u.output_tokens:,} out. "
        f"This report is informational and is not legal advice._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
