"""Render a run summary to JSON and human-readable Markdown."""

from __future__ import annotations

import json

from crm_automation.models import Decision, RunSummary

_DECISION_BADGE = {
    Decision.PROPOSED: "📋 Proposed",
    Decision.APPROVED: "✅ Approved",
    Decision.DENIED: "🚫 Denied",
    Decision.EXECUTED: "✅ Executed",
    Decision.SKIPPED: "⏭️ Skipped",
    Decision.FAILED: "❌ Failed",
}


def render_json(summary: RunSummary) -> str:
    """Serialize the full run summary as pretty JSON."""
    return json.dumps(summary.model_dump(mode="json"), indent=2)


def _cell(text: str, limit: int = 90) -> str:
    text = " ".join((text or "").split())
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text.replace("|", "\\|")


def render_markdown(summary: RunSummary) -> str:
    lines: list[str] = []
    mode = "Dry run (nothing executed)" if summary.dry_run else "Live (human-gated)"

    lines.append("# CRM Automation Run")
    lines.append("")
    lines.append(f"**Source:** {summary.source}  ")
    lines.append(f"**Mode:** {mode}  ")
    lines.append(f"**Model:** `{summary.model}`  ")
    lines.append(f"**Generated:** {summary.started_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")
    lines.append(
        f"Scanned **{summary.contacts_scanned}** contact(s) and "
        f"**{summary.deals_scanned}** deal(s); detected **{len(summary.triggers)}** "
        f"trigger(s) and proposed **{len(summary.proposed)}** action(s)."
    )
    lines.append("")

    # -- Triggers --
    lines.append("## Triggers Detected")
    lines.append("")
    if summary.triggers:
        lines.append("| Type | Target | Detail |")
        lines.append("|---|---|---|")
        for t in summary.triggers:
            lines.append(
                f"| {t.type.value} | {_cell(t.target_id, 20)} | {_cell(t.detail, 110)} |"
            )
        lines.append("")
    else:
        lines.append("_No triggers detected._")
        lines.append("")

    # -- Actions / audit --
    lines.append("## Proposed Actions & Decisions")
    lines.append("")
    if summary.audit:
        lines.append("| Rule | Action | Target | Decision | Result |")
        lines.append("|---|---|---|---|---|")
        for a in summary.audit:
            badge = _DECISION_BADGE.get(a.decision, a.decision.value)
            lines.append(
                f"| {_cell(a.rule_name, 28)} | {a.action_type.value} | "
                f"{_cell(a.target_id, 20)} | {badge} | {_cell(a.result, 90)} |"
            )
        lines.append("")
    else:
        lines.append("_No actions proposed._")
        lines.append("")

    # -- Email drafts (review queue) --
    drafts = [a for a in summary.audit if a.params.get("draft_body")]
    if drafts:
        lines.append("## Drafted Emails — For Your Review (not sent)")
        lines.append("")
        for a in drafts:
            lines.append(f"### {a.target_id} — {a.params.get('draft_subject', '(no subject)')}")
            lines.append("")
            lines.append(str(a.params.get("draft_body", "")))
            lines.append("")

    counts = {d: len(summary.by_decision(d)) for d in Decision}
    lines.append("---")
    lines.append(
        "_Generated by the Lumifie Consulting CRM Automation Agent. "
        f"Executed: {counts[Decision.EXECUTED]}, "
        f"denied: {counts[Decision.DENIED]}, "
        f"proposed-only: {counts[Decision.PROPOSED]}, "
        f"failed: {counts[Decision.FAILED]}. "
        "External actions are human-gated; emails are drafts only._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
