"""Render a PipelineResult to JSON and an executive Markdown briefing."""

from __future__ import annotations

from sales_ops.models import Decision, PipelineResult

_DECISION_ICON = {
    Decision.EXECUTED: "✅",
    Decision.DRY_RUN: "🟦",
    Decision.DENIED: "🚫",
    Decision.FAILED: "❌",
    Decision.SKIPPED: "⏭️",
    Decision.APPROVED: "✅",
}


def render_json(result: PipelineResult, *, indent: int = 2) -> str:
    return result.model_dump_json(indent=indent)


def render_markdown(result: PipelineResult) -> str:
    r = result.report
    lines: list[str] = []
    mode = "🟦 DRY RUN (nothing executed)" if result.dry_run else "🟢 LIVE"

    lines.append(f"# Sales Pipeline Briefing — {result.pipeline_id}")
    lines.append("")
    lines.append(f"**Mode:** {mode}  ")
    lines.append(f"**Model:** `{result.model}`  ")
    if r:
        lines.append(f"**Generated:** {r.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    if r:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(r.summary)
        lines.append("")

        m = r.metrics
        lines.append("## Pipeline Metrics")
        lines.append("")
        lines.append(f"- **Leads prospected:** {m.leads_prospected}")
        lines.append(f"- **Sequences drafted:** {m.sequences_drafted}")
        lines.append(f"- **Replies processed:** {m.replies_processed}")
        lines.append(
            f"- **Actions executed:** {m.actions_executed} / {m.actions_proposed} proposed"
        )
        if m.by_stage:
            lines.append(f"- **By stage:** {', '.join(f'{k}: {v}' for k, v in m.by_stage.items())}")
        if m.by_reply_intent:
            lines.append(
                "- **Reply intents:** "
                + ", ".join(f"{k}: {v}" for k, v in m.by_reply_intent.items())
            )
        lines.append("")

        if r.recommended_next_actions:
            lines.append("## 🆕 Recommended Next Actions")
            lines.append("")
            for a in r.recommended_next_actions:
                lines.append(f"- {a}")
            lines.append("")

        if r.stale_deals:
            lines.append("## ⏳ Stale Deals")
            lines.append("")
            for d in r.stale_deals:
                lines.append(
                    f"- **{d.company}** — {d.days_stale}d in `{d.stage}` (lead {d.lead_id})"
                )
            lines.append("")

    # Leads
    if result.leads:
        lines.append("## Leads")
        lines.append("")
        lines.append("| Rank | Company | ICP fit | Tier | Stage |")
        lines.append("|---|---|---|---|---|")
        for lead in result.leads:
            lines.append(
                f"| {lead.rank} | {lead.company} | {lead.icp_fit} "
                f"| {lead.tier} | {lead.stage.value} |"
            )
        lines.append("")

    # Outreach preview (first lead's first email)
    if result.sequences and result.sequences[0].steps:
        seq = result.sequences[0]
        step = seq.steps[0]
        lines.append("## Sample Outreach (top lead)")
        lines.append("")
        if step.subject:
            lines.append(f"_Subject:_ {step.subject}")
            lines.append("")
        lines.append(step.body)
        lines.append("")

    # Replies
    if result.replies:
        lines.append("## Replies")
        lines.append("")
        for rep in result.replies:
            lines.append(f"- **{rep.from_email}** → `{rep.intent.value}` — {rep.suggested_action}")
        lines.append("")

    # Action log (the audit-visible decisions)
    if result.actions:
        lines.append("## Action Log (approval-gated)")
        lines.append("")
        for a in result.actions:
            icon = _DECISION_ICON.get(a.decision, "•")
            lines.append(
                f"- {icon} `{a.type.value}` [{a.lead_id}] — {a.decision.value}: {a.detail}"
            )
        lines.append("")

    u = result.token_usage
    lines.append("---")
    lines.append(
        f"_Generated by the Lumifie Consulting Sales-Ops Multi-Agent. "
        f"Tokens: {u.get('input_tokens', 0):,} in / {u.get('output_tokens', 0):,} out. "
        f"Every external action passed the human approval gate (or was withheld in dry-run)._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
