"""Render a monitoring digest to JSON and Markdown.

The JSON mirrors the Markdown: header, the new-this-week impacts, the full
watchlist, and the sources checked.
"""

from __future__ import annotations

import json

from reg_monitor.models import Digest, ImpactStatement, Relevance

_BADGE = {
    Relevance.HIGH: "🔴 High",
    Relevance.MEDIUM: "🟡 Medium",
    Relevance.LOW: "🟢 Low",
}


def render_json(digest: Digest) -> str:
    """Serialize the digest as pretty JSON (mirrors the Markdown layout)."""
    payload = {
        "business": {
            "industry": digest.profile.industry,
            "location": digest.profile.location,
            "operational_keywords": digest.profile.operational_keywords,
        },
        "run_date": digest.generated_at.strftime("%Y-%m-%d"),
        "generated_at": digest.generated_at.isoformat(),
        "model": digest.model,
        "lookback_days": digest.lookback_days,
        "is_baseline": digest.is_baseline,
        "plan": digest.plan.model_dump(mode="json"),
        "new_this_week": [i.model_dump(mode="json") for i in digest.new_by_relevance()],
        "full_watchlist": [i.model_dump(mode="json") for i in digest.impacts_by_relevance()],
        "sources_checked": digest.sources_checked,
        "token_usage": digest.token_usage,
    }
    return json.dumps(payload, indent=2)


def _impact_block(lines: list[str], idx: int, impact: ImpactStatement) -> None:
    badge = _BADGE[impact.relevance]
    when = f" · {impact.date}" if impact.date else ""
    lines.append(f"### {idx}. {badge} — {impact.title}{when}")
    lines.append("")
    lines.append(impact.plain_english)
    lines.append("")
    lines.append(f"**Recommended action:** {impact.recommended_action}")
    if impact.url:
        lines.append("")
        lines.append(f"[Source]({impact.url})")
    lines.append("")


def render_markdown(digest: Digest) -> str:
    p = digest.profile
    lines: list[str] = []

    lines.append(f"# Regulatory Digest — {p.industry} ({p.location})")
    lines.append("")
    lines.append(f"**Business:** {p.industry} in {p.location}  ")
    if p.operational_keywords:
        lines.append(f"**Watching:** {', '.join(p.operational_keywords)}  ")
    lines.append(f"**Run date:** {digest.generated_at.strftime('%Y-%m-%d')}  ")
    lines.append(f"**Lookback window:** last {digest.lookback_days} day(s)  ")
    lines.append(f"**Model:** `{digest.model}`  ")
    lines.append(f"**Items on watchlist:** {len(digest.impacts)}")
    lines.append("")

    # -- New this week --
    lines.append("## 🆕 New This Week")
    lines.append("")
    new = digest.new_by_relevance()
    if digest.is_baseline:
        lines.append(
            "_This is the baseline run — everything below is new. Future runs will "
            "highlight only what changed since the previous digest._"
        )
        lines.append("")
    if new:
        for i, impact in enumerate(new, start=1):
            _impact_block(lines, i, impact)
    else:
        lines.append("_No new regulatory changes since the last run._")
        lines.append("")

    # -- Full watchlist --
    lines.append("## Full Watchlist")
    lines.append("")
    watch = digest.impacts_by_relevance()
    if watch:
        for i, impact in enumerate(watch, start=1):
            _impact_block(lines, i, impact)
    else:
        lines.append("_No relevant regulatory items identified in this window._")
        lines.append("")

    # -- Sources --
    lines.append("## Sources Checked")
    lines.append("")
    if digest.sources_checked:
        for s in digest.sources_checked:
            lines.append(f"- {s}")
    else:
        lines.append("_No sources were checked._")
    lines.append("")

    u = digest.token_usage
    lines.append("---")
    lines.append(
        "_Generated by the Lumifie Consulting Regulatory Monitor Agent. "
        f"Tokens: {u.get('input_tokens', 0):,} in / {u.get('output_tokens', 0):,} out. "
        "Informational only — not legal advice; verify before acting._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
