"""Render a LeadReport to JSON and Markdown."""

from __future__ import annotations

from lead_research.models import LeadReport


def render_json(report: LeadReport, *, indent: int = 2) -> str:
    return report.model_dump_json(indent=indent)


def _fit_badge(score: int) -> str:
    if score >= 75:
        return f"🟢 Strong ({score}/100)"
    if score >= 50:
        return f"🟡 Moderate ({score}/100)"
    return f"🔴 Weak ({score}/100)"


def render_markdown(report: LeadReport) -> str:
    e = report.enrichment
    s = report.icp_score
    o = report.outreach
    lines: list[str] = []

    lines.append(f"# Lead Research — {e.company_name}")
    lines.append("")
    lines.append(f"**URL:** {report.company_url}  ")
    lines.append(f"**ICP fit:** {_fit_badge(s.fit_score)} — tier {s.tier}"
                 + ("  ·  ⛔ disqualified" if s.disqualified else "") + "  ")
    lines.append(f"**ICP:** {report.icp_name}  ")
    lines.append(f"**Model:** `{report.model}`  ")
    lines.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    lines.append("## ICP Fit")
    lines.append("")
    lines.append(s.reasoning)
    lines.append("")
    if s.matched_criteria:
        lines.append("**Matches:** " + ", ".join(s.matched_criteria))
    if s.gaps:
        lines.append("**Gaps:** " + ", ".join(s.gaps))
    lines.append("")

    lines.append("## Company Snapshot")
    lines.append("")
    if e.industry:
        lines.append(f"- **Industry:** {e.industry}")
    lines.append(f"- **Value proposition:** {e.value_proposition}")
    if e.key_executives:
        execs = ", ".join(f"{x.name} ({x.title})" for x in e.key_executives)
        lines.append(f"- **Key executives:** {execs}")
    if e.recent_news:
        lines.append("- **Recent news:**")
        for n in e.recent_news:
            lines.append(f"  - {n}")
    if e.summary:
        lines.append("")
        lines.append(e.summary)
    lines.append("")

    lines.append("## Outreach")
    lines.append("")
    lines.append("**Email**")
    lines.append("")
    lines.append(f"_Subject:_ {o.email_subject}")
    lines.append("")
    lines.append(o.email_body)
    lines.append("")
    lines.append("**LinkedIn**")
    lines.append("")
    lines.append(o.linkedin_message)
    lines.append("")
    if o.personalization_signals:
        lines.append("**Personalization signals used:** " + ", ".join(o.personalization_signals))
        lines.append("")

    if report.sources:
        lines.append("## Sources")
        lines.append("")
        for url in report.sources:
            lines.append(f"- {url}")
        lines.append("")

    u = report.token_usage
    lines.append("---")
    lines.append(
        f"_Generated by the Lumifie Consulting Lead Research Agent. "
        f"Tokens: {u.get('input_tokens', 0):,} in / {u.get('output_tokens', 0):,} out. "
        f"Verify signals before outreach._"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_json", "render_markdown"]
